#!/usr/bin/env python3
"""Regenerate src/lib/sitemap-exclusions.ts from live probes.

Probes every model_id returned by the API against the live site and writes
the set of dead (404) + legacy (redirecting) IDs that must be excluded from
sitemap.xml. Run:  python3 tools/gen_sitemap_exclusions.py
"""
import json
import subprocess
import sys
import urllib.request
import urllib.parse

SITE = "https://www.inferenceindexer.ai"
API = "https://api.inferenceindexer.ai"

def api_models():
    ids, offset = [], 0
    while True:
        url = f"{API}/v1/models?limit=500&offset={offset}"
        try:
            with urllib.request.urlopen(url, timeout=30) as r:
                data = json.load(r)
        except Exception as e:
            print(f"API error at offset {offset}: {e}", file=sys.stderr)
            break
        models = data.get("models", [])
        if not models:
            break
        ids += [m["model_id"] for m in models]
        if len(models) < 500:
            break
        offset += 500
    return ids

def probe(id_):
    path = urllib.parse.quote(f"/models/{id_}", safe="/")
    cmd = ["curl", "-s", "-o", "/dev/null", "-w", "%{http_code}",
           "-m", "20", f"{SITE}{path}"]
    try:
        return subprocess.run(cmd, capture_output=True, text=True, timeout=25).stdout.strip()
    except Exception:
        return "000"

def main():
    ids = api_models()
    print(f"probing {len(ids)} model ids against {SITE} ...")
    dead, legacy, live = [], [], []
    for i, id_ in enumerate(ids):
        code = probe(id_)
        if code == "404":
            dead.append(id_)
        elif code in ("301", "308"):
            legacy.append(id_)
        elif code == "200":
            live.append(id_)
        if (i + 1) % 100 == 0:
            print(f"  {i+1}/{len(ids)}")
    dead += [i for i in ids if i not in live and i not in dead and i not in legacy]
    ts = ["// AUTO-GENERATED by tools/gen_sitemap_exclusions.py — do not edit by hand.",
          "// Regenerate after model catalogue changes (python3 tools/gen_sitemap_exclusions.py).",
          "// IDs below returned HTTP 404 on the live site or 301/308 to another slug.",
          "// They must not appear in sitemap.xml.",
          "export const SITEMAP_EXCLUDED_MODEL_IDS: ReadonlySet<string> = new Set(["]
    ts += [f'  "{i}",' for i in sorted(set(dead) | set(legacy))]
    ts.append("]);")
    out = "src/lib/sitemap-exclusions.ts"
    with open(out, "w") as f:
        f.write("\n".join(ts) + "\n")
    print(f"wrote {out}: {len(set(dead) | set(legacy))} exclusions "
          f"({len(dead)} dead, {len(legacy)} legacy redirecting, {len(live)} live)")

if __name__ == "__main__":
    main()
